## Example Config file
baseURL: "https://example.com"
theme: "terminalcv"
title: "yimila.dev"

params:
  version: "4.0.0"
  description: "yimila's personal website"
  blog: true
  prompt:
    core:
      text: "guest@yimila.dev"
      color: "pink"
      before: "["
      beforeColor: "red"
      after: '\]'
      afterColor: "red"
      # separator: '-'
    separator:
      text: "-"
      # color:
    path:
      before: "["
      beforeColor: "red"
      text: "~/yimiladev"
      color: "blue"
      after: '\]'
      afterColor: "red"
    extra:
      text: ": "
      color: "orange"

  # promptColor: grey
  # promptSimbols: ":~$"
  # promptSimbolsColor: grey
  # startxLocation: https://example.com
  # useLess: true
  listLS: true
  #exitLocation: "about:blank"
  exitMessage: "[session completed, the browserwindow can be safely closed]"
  source: true
  #use a â€Ž (blank character) if your first character of the ascii art is a whitespace
  greeting: |
    01111001011010010110110101101001011011000110000100101110011001000110010101110110 
             _________ _______ _________ _        _______     ______   _______          
    |\     /|\__   __/(       )\__   __/( \      (  ___  )   (  __  \ (  ____ \|\     /|
    ( \   / )   ) (   | () () |   ) (   | (      | (   ) |   | (  \  )| (    \/| )   ( |
     \ (_) /    | |   | || || |   | |   | |      | (___) |   | |   ) || (__    | |   | |
      \   /     | |   | |(_)| |   | |   | |      |  ___  |   | |   | ||  __)   ( (   ) )
       ) (      | |   | |   | |   | |   | |      | (   ) |   | |   ) || (       \ \_/ / 
       | |   ___) (___| )   ( |___) (___| (____/\| )   ( | _ | (__/  )| (____/\  \   /  
       \_/   \_______/|/     \|\_______/(_______/|/     \|(_)(______/ (_______/   \_/   



    welcome to yimila.dev!

    type 'help' for a list of available commands

  bootsequence: |
    user request detected
    fucks sake not again
    -----------------------
    cloudnetwork [ready]
    ---------
    cloudinstance [ready]
    -----------------------
    vps seems to work

    initiating yimila.dev startup
    yimila.dev current tranche: 4.0.0: NOV20
    loglevel = opseclike

    -------------------------------------
    trapped under ice
    comfortably cold
    i've gone as low as you can go
    feel no remorse
    no sense of shame
    time's gonna wash away all pain
    -------------------------------------

    yimdevboot1: [ready]
    yimdevboot2: [ready]
    webserver: [ready] 
    hugo: [ready]
    yimila.dev: [ready]
    alright come in
    \\// \\// \\//
    //\\ //\\ //\\

  whois:
    # settings:
    #   useLess: true
    details:
      name: "yimila"
      profession: "gamedev"
      location: "[REDACTED]"
      email: "yimila@yimila.dev"
      homelink: "https://yimila.dev"
      description: |
        master of none

  social:
    # settings:
    #   useLess: true
    #   hideName: true
    details:
      - name: "github"
        url: "https://github.com/yimila"
      - name: "bluesky"
        url: "https://bsky.app/profile/yimila.dev"

  education:
    details:
      - courseName: ECE 
        color: lime
        date: undergrad since 2025
        description: i like the way this sucks

  skills:
    settings:
      useLess: false
    details:
      - name: coding
        color: green
        percentage: 54
        description: c & gdscript

      - name: drawing
        color: pink
        percentage: 31
        description: professional tracer

  softskills:
    # settings:
    #   useLess: true
    details:
      - name: social skills 
        color: red
        percentage: 34
        #description:

      - name: interactions with girls
        color: pink
        percentage: 22
        #description: Description

  languages:
    # settings:
    #   useLess: true
    details:
      - name: english
        color: Blue
        percentage: 100
        #description:

      - name: turkish
        color: Red
        percentage: 100

      - name: russian
        color: White
        percentage: 10

  projects:
    # settings:
    #   useLess: true
    details:
      - title: 3demo
        color: purple
        date: since 2024
        link: https://yimila.itch.io/3demo
        description: 3d demonstration

      - title: yimila.dev
        color: cyan
        date: since 2025
        link: https://yimila.dev
        description: you're looking at it


  #certifications:
    # settings:
    #   useLess: true
    #details:
      #- certName: Example Cert
        #company: Example Certifying Company
        #date: Date of Completion
        #badge: https://www.link.to.badge
        #description: Lorem Ipsum

  #misc:
    # settings:
    #   useLess: true
    #commandName: newcommand
    #title: "This Section can have a different command name"
    #titleColor: teal
    #content: |
      #Here the title and the content can have different colors
      #The content can be multi

      #line

      #And spaces       will be respected as well
      #This section will have the default command: misc
      #but you can name it something else with the property
      #commandName: <String>
      #Give it a shot and try and uncomment the line 
      #commandName: newcommand
      #now instead of misc you can execute the newcommand for this section
      #Auto completion will know it too! :D

    #contentColor: orange
